version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - coolify
      - bgcwg4k8ckk0skss4w0kgcso
    restart: unless-stopped

networks:
  coolify:
    external: true
  bgcwg4k8ckk0skss4w0kgcso:
    external: true

## Ajuste para que o sistema rode na rede correta.
## docker network connect bgcwg4k8ckk0skss4w0kgcso noow000ogg08koo80wock0s0-203841983997
## docker restart noow000ogg08koo80wock0s0-203841983997
